{{ if and .Values.rollout.enabled .Values.rollout.smokeTest.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}-smoke-test
spec:
  args:
  - name: service-name
  metrics:
  - name: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}-smoke-test
    successCondition: "result.ok"
    provider:
      web:
        url: {{ .Values.rollout.smokeTest.url }}
        jsonPath: "{$.data}"
{{ end }}