apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
annotations:
spec:
  rules:
    - host: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}-{{ .Release.Namespace }}.{{ .Values.domain }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}
