{{ if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
    app-version: {{ .Values.version }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.pod.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.url }}
              port: {{ .Values.pod.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.url }}
              port: {{ .Values.pod.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: APP_CONFIG_HEALTH_LIVENESS
              value: {{ .Values.config.health.liveness | quote }}
            - name: APP_CONFIG_HEALTH_READINESS
              value: {{ .Values.config.health.readiness | quote }}
          {{- if .Values.env }}
          {{- range $key,$val := .Values.env }}
            - name: {{ $key }}
              value: {{ tpl ($val|toString) $ | quote }}
          {{- end }}
          {{- end }}
  strategy:
    blueGreen:
      activeService: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
      previewService: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}-rollout
      autoPromotionEnabled: {{ .Values.rollout.autoPromotionEnabled }}
      {{ if .Values.rollout.smokeTest.enabled }}
      prePromotionAnalysis:
        templates:
        - templateName: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}-smoke-test
        args:
        - name: service-name
          value: {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}-rollout
      {{ end }}
{{ end }}